## Introduction

In [1]:
import numpy as np
print(np.__version__)

1.19.2


In [2]:
a = np.array([0, 1, 2, 3])
print(a)

[0 1 2 3]


In [3]:
L = range(1000)
%timeit [i**2 for i in L]

665 µs ± 21.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
a = np.arange(1000)
%timeit a**2

3.87 µs ± 178 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
# numpy
# np.lookfor('eigen')# uncomment me to try

In [6]:
# jupyter
# np.con*?# uncomment me to try

In [7]:
# jupyter
# np.concatenate?# uncomment me to try

## Creating arrays

### Manual construction
* numpy.array()

In [8]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [9]:
print(a)

[0 1 2 3]


In [10]:
repr(a)

'array([0, 1, 2, 3])'

In [11]:
str(a)

'[0 1 2 3]'

In [12]:
a.ndim

1

In [13]:
a.shape

(4,)

In [14]:
len(a)

4

In [15]:
b = np.array([[0, 1, 2], [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
print(b)

[[0 1 2]
 [3 4 5]]


In [17]:
b.ndim

2

In [18]:
b.shape

(2, 3)

In [19]:
len(b)

2

In [20]:
c = np.array([[[1], [2]], [[3], [4]]])
c

array([[[1],
        [2]],

       [[3],
        [4]]])

In [21]:
c.ndim

3

In [22]:
c.shape

(2, 2, 1)

In [23]:
len(c)

2

In [24]:
d = np.array([[1],[2],[3],[4]])
d

array([[1],
       [2],
       [3],
       [4]])

In [25]:
d.ndim

2

In [26]:
d.shape

(4, 1)

### Functions for creating arrays
* numpy.arange()
* numpy.linspace()
* numpy.ones()
* numpy.zeros()
* numpy.eye()
* numpy.empty()
* numpy.full()
* numpy.ones_like()
* numpy.zeros_like()
* numpy.empty_like()
* numpy.full_like()

In [27]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
b = np.arange(1, 9, 2)
b

array([1, 3, 5, 7])

In [29]:
c = np.linspace(0, 1, 11)
c

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [30]:
a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
b = np.zeros((2, 2))
b

array([[0., 0.],
       [0., 0.]])

In [32]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
a = np.empty([2, 2])
a

array([[0., 0.],
       [0., 0.]])

In [34]:
a = np.full((2, 2), 1.23)
a

array([[1.23, 1.23],
       [1.23, 1.23]])

In [35]:
a = np.ones((3, 3))
print(a)
b = np.zeros_like(a)
b

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Indexing and slicing

## Numerical operations on arrays

In [36]:
a = np.array([1, 2, 3, 4])
a + 1 

array([2, 3, 4, 5])

In [37]:
x = np.linspace(0, np.pi, 10)
x

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

In [38]:
np.sin(x)

array([0.00000000e+00, 3.42020143e-01, 6.42787610e-01, 8.66025404e-01,
       9.84807753e-01, 9.84807753e-01, 8.66025404e-01, 6.42787610e-01,
       3.42020143e-01, 1.22464680e-16])