In [1]:
import numpy as np
from scipy.linalg import eig, eigh
from scipy.sparse.linalg import eigs, eigsh

In [ ]:
np.random.seed(0)
D = 50
n = 3
dim = D**n
X = np.random.random((dim,dim)) - 0.5
X = np.dot(X, X.T) #create a symmetric matrix

In [10]:
evals_all, evecs_all = eigh(X)
print(evals_all[-3:])

In [8]:
evals_large, evecs_large = eigsh(X, 3, which='LM')


print(evals_large)

print(np.dot(evecs_large.T, evecs_all[:,-3:]))

[12.39842126 13.58834325 17.21901167]
[12.39842126 13.58834325 17.21901167]
[[ 1.00000000e+00 -2.91433544e-16 -7.84095011e-16]
 [-2.90045765e-15 -1.00000000e+00  8.82974249e-16]
 [ 5.82867088e-16  8.10115863e-16  1.00000000e+00]]
