# Introduction to NumPy
## Linear Algebra

* Author: Pochung Chen
* Email: pcchen@phys.nthu.edu.tw

In [2]:
import numpy as np

## Tensordot
* https://numpy.org/doc/stable/reference/generated/numpy.tensordot.html

In [3]:
a = np.eye(2)
b = np.ones((2,2))

In [4]:
np.kron(a, b)

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [5]:
c = np.tensordot(a, b, 0)
c.reshape((4, 4))

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.]])

In [6]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [7]:
b=np.array([[0, 5], [6, 7]])
b

array([[0, 5],
       [6, 7]])

In [8]:
np.kron(a, b)

array([[ 0,  5,  0, 10],
       [ 6,  7, 12, 14],
       [ 0, 15,  0, 20],
       [18, 21, 24, 28]])

## transpose, moveaxis, swapaxes
* https://numpy.org/doc/stable/reference/generated/numpy.transpose.html
* https://numpy.org/doc/stable/reference/generated/numpy.moveaxis.html#numpy.moveaxis
* https://numpy.org/doc/stable/reference/generated/numpy.swapaxes.html#numpy.swapaxes

In [12]:
x = np.zeros((3, 4, 5))
print(np.moveaxis(x, 0, -1).shape)
print(np.moveaxis(x, -1, 0).shape)

(4, 5, 3)
(5, 3, 4)


In [14]:
(4,5,3)[-1]

3

### Matrix multiplication
numpy.matrix()
**It is no longer recommended to use this class, even for linear algebra. Instead use regular arrays. The class may be removed in the future.**

* numpy.matmul()
* numpy.dot()
* numpy.vdot()
* numpy.tensordot()

#### `numpy.dot(1D, 1D)` --> inner product of vectors (without complex conjugation)

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

32

In [4]:
a = np.array([2j, 3j])
b = np.array([2j, 3j])
np.dot(a, b)

(-13+0j)

#### `numpy.vdot(1D, 1D)` --> inner product of vectors (complex conjugate of the first argument is used)

In [5]:
a = np.array([2j, 3j])
b = np.array([2j, 3j])
np.vdot(a, b)

(13+0j)

### `numpy.matmul(2D, 2D)` --> matrix multiplication

In [6]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])
np.matmul(a, b)

array([[4, 1],
       [2, 2]])

#### Use '@' operator

In [7]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])
a @ b 

array([[4, 1],
       [2, 2]])

#### `numpy.matmul(2D, 1D)` or `numpy.matmul(1D, 2D)`--> matrix multiplication

In [8]:
a = np.array([[1, 2],
              [0, 1]])
b = np.array([1, 2])
b.shape

(2,)

In [9]:
np.matmul(a, b)

array([5, 2])

In [10]:
a @ b

array([5, 2])

In [11]:
np.matmul(b, a)

array([1, 4])

In [12]:
b @ a 

array([1, 4])

In [13]:
a = np.array([[1, 2],
              [0, 1]])
b = np.array([[1], [2]])
print(b)
b.shape

[[1]
 [2]]


(2, 1)

In [14]:
np.matmul(a, b)

array([[5],
       [2]])

In [15]:
a @ b

array([[5],
       [2]])

In [16]:
np.matmul(b, a)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [ ]:
b @ a 

### Determinant

In [17]:
a = np.array([[1, 2], [3, 4]])
np.linalg.det(a)

-2.0000000000000004

## Sparse eigenvalue problems with Arpack (scipy)